services:
  web:
    networks:
      - gameplot
    build: .
    ports:
      - "5000:5000"
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock

        # Rebuild the image if the build steps change
        - action: rebuild
          path: ./Dockerfile

    environment:
      FLASK_APP: gameplot
      FLASK_DATABASE_HOST: db
      FLASK_DATABASE_PORT: 5432
      FLASK_DATABASE_USER: postgres
      FLASK_DATABASE_NAME: gameplot
      FLASK_DATABASE_PASSWORD: password
      

  db:
    image: postgres:latest
    restart: always
    ports:
      - 15432:5432
    networks:
      - gameplot
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    networks:
      - gameplot
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json

volumes:
  postgresql:

networks:
  gameplot:

configs:
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Minimally Defined Server",
            "Group": "Servers",
            "Port": 5432,
            "Username": "postgres",
            "Host": "db",
            "MaintenanceDB": "postgres",
            "ConnectionParameters": {
                "sslmode": "prefer",
                "connect_timeout": 10
            }
          }
        }
      }