CREATE TABLE games (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(128) NOT NULL,
    description varchar(2048),
    steam_url   varchar(128),
    itch_url    varchar(128),
    CHECK (NOT (steam_url IS NULL AND itch_url IS NULL))
);