CREATE TABLE games (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        char(256) NOT NULL,
    description char(2048),
    steam_url   char(256),
    itch_url    char(256),
    CHECK (NOT (steam_url IS NULL AND itch_url IS NULL))
);

CREATE TYPE jobstatus AS ENUM ('pending', 'active', 'done', 'errored');

CREATE TABLE jobs (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    payload         json,
    status          jobstatus,
    insert_ts       timestamp,
    pickup_ts       timestamp,
    completion_ts   timestamp,
    result          varchar
);